# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: rnaseq-3.2.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - conda-forge::pymdown-extensions=7.1
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.9
  - bioconda::samtools=1.11
  - bioconda::star=2.7.6a
  - bioconda::hisat2=2.2.1
  - bioconda::bowtie2=2.4.2
  - bioconda::bowtie=1.3.0
  - bioconda::picard=2.23.8
  - bioconda::preseq=2.0.3
  - bioconda::rseqc=4.0.0
  - bioconda::subread=2.0.1
  - bioconda::htseq=0.12.4

# R-packages
  - r-base=4.0.3
  - bioconda::bioconductor-dupradar=1.18.0
  - conda-forge::r-data.table=1.13.0
  - conda-forge::r-gplots=3.1.0
  - bioconda::bioconductor-rtracklayer=1.48.0
  - bioconda::bioconductor-genomicfeatures=1.40.0
  - bioconda::bioconductor-edger=3.30.0
  - bioconda::bioconductor-deseq2=1.28.0

