package colorlog


class MonoChrome extends Presets {
    String getReset() { "" }
    String getDim() { "" }
    String getBlack() { "" }
    String getBlackBold() { "" }
    String getBlackBackground() { "" }
    String getBlackBright() { "" }
    String getBlackUnderlined() { "" }
    String getBlackBoldBright() { "" }
    String getBlackBackgroundBright() { "" }
    String getGreen() { "" }
    String getGreenBold() { "" }
    String getGreenBackground() { "" }
    String getGreenBright() { "" }
    String getGreenUnderlined() { "" }
    String getGreenBoldBright() { "" }
    String getGreenBackgroundBright() { "" }
    String getYellow() { "" }
    String getYellowBold() { "" }
    String getYellowBackground() { "" }
    String getYellowBright() { "" }
    String getYellowUnderlined() { "" }
    String getYellowBoldBright() { "" }
    String getYellowBackgroundBright() { "" }
    String getBlue() { "" }
    String getBlueBold() { "" }
    String getBlueBackground() { "" }
    String getBlueBright() { "" }
    String getBlueUnderlined() { "" }
    String getBlueBoldBright() { "" }
    String getBlueBackgroundBright() { "" }
    String getPurple() { "" }
    String getPurpleBold() { "" }
    String getPurpleBackground() { "" }
    String getPurpleBright() { "" }
    String getPurpleUnderlined() { "" }
    String getPurpleBoldBright() { "" }
    String getPurpleBackgroundBright() { "" }
    String getCyan() { "" }
    String getCyanBold() { "" }
    String getCyanBackground() { "" }
    String getCyanBright() { "" }
    String getCyanUnderlined() { "" }
    String getCyanBoldBright() { "" }
    String getCyanBackgroundBright() { "" }
    String getWhite() { "" }
    String getWhiteBold() { "" }
    String getWhiteBackground() { "" }
    String getWhiteBright() { "" }
    String getWhiteUnderlined() { "" }
    String getWhiteBoldBright() { "" }
    String getWhiteBackgroundBright() { "" }
    String getRed() { "" }
    String getRedBold() { "" }
    String getRedBackground() { "" }
    String getRedBright() { "" }
    String getRedUnderlined() { "" }
    String getRedBoldBright() { "" }
    String getRedBackgroundBright() { "" }
}