package colorlog


abstract class Presets {

    abstract String getReset()
    abstract String getBlack()
    abstract String getBlackBold()
    abstract String getBlackBackground()
    abstract String getBlackBright()
    abstract String getBlackUnderlined()
    abstract String getBlackBoldBright()
    abstract String getBlackBackgroundBright()
    abstract String getGreen()
    abstract String getGreenBold()
    abstract String getGreenBackground()
    abstract String getGreenBright()
    abstract String getGreenUnderlined()
    abstract String getGreenBoldBright()
    abstract String getGreenBackgroundBright()
    abstract String getYellow()
    abstract String getYellowBold()
    abstract String getYellowBackground()
    abstract String getYellowBright()
    abstract String getYellowUnderlined()
    abstract String getYellowBoldBright()
    abstract String getYellowBackgroundBright()
    abstract String getBlue()
    abstract String getBlueBold()
    abstract String getBlueBackground()
    abstract String getBlueBright()
    abstract String getBlueUnderlined()
    abstract String getBlueBoldBright()
    abstract String getBlueBackgroundBright()
    abstract String getPurple()
    abstract String getPurpleBold()
    abstract String getPurpleBackground()
    abstract String getPurpleBright()
    abstract String getPurpleUnderlined()
    abstract String getPurpleBoldBright()
    abstract String getPurpleBackgroundBright()
    abstract String getCyan()
    abstract String getCyanBold()
    abstract String getCyanBackground()
    abstract String getCyanBright()
    abstract String getCyanUnderlined()
    abstract String getCyanBoldBright()
    abstract String getCyanBackgroundBright()
    abstract String getWhite()
    abstract String getWhiteBold()
    abstract String getWhiteBackground()
    abstract String getWhiteBright()
    abstract String getWhiteUnderlined()
    abstract String getWhiteBoldBright()
    abstract String getWhiteBackgroundBright()
    abstract String getRed()
    abstract String getRedBold()
    abstract String getRedBackground()
    abstract String getRedBright()
    abstract String getRedUnderlined()
    abstract String getRedBoldBright()
    abstract String getRedBackgroundBright()

    Map palette() {
        return this.getProperties()
                .findAll{ key,value ->
                    key != 'class' && key != 'map' && key != 'empty' && key != 'map'}
    }
}